#!/bin/sh

# Switch to $WORKSPACE with dmenu using tmuxstart https://github.com/treyhunner/tmuxstart

PROJECT_DIR=$HOME/.tmuxstart
FONT="Inconsolata-16"
WORKSPACE=$(
  stest -fl $PROJECT_DIR | dmenu \
    -nb '#002b36' -nf '#839496' -sb '#073642' -sf '#cb4b16' \
    -fn $FONT -i -p "Workspace"
)

if [ ! -z "$WORKSPACE" ]; then
  (ls -1 $PROJECT_DIR | grep -q "$WORKSPACE") && (tmuxstart $WORKSPACE)
fi
